/**
 * The MIT License
 *
 * Copyright (C) 2015 Asterios Raptis
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *  *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *  *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package de.alpharogroup.address.book.init;

public class DeZipcodeBean
{
	/** The iso3166 name with two characters. */
	private String iso3166A2name;

	private String zipcode;

	private String city;

	private String latitude;

	private String longitude;

	public String getCity()
	{
		return city;
	}

	public String getIso3166A2name()
	{
		return iso3166A2name;
	}

	public String getLatitude()
	{
		return latitude;
	}

	public String getLongitude()
	{
		return longitude;
	}

	public String getZipcode()
	{
		return zipcode;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public void setIso3166A2name(String iso3166a2name)
	{
		iso3166A2name = iso3166a2name;
	}

	public void setLatitude(String latitude)
	{
		this.latitude = latitude;
	}

	public void setLongitude(String longitude)
	{
		this.longitude = longitude;
	}

	public void setZipcode(String zipcode)
	{
		this.zipcode = zipcode;
	}

	/**
	 * @generated by CodeSugar http://sourceforge.net/projects/codesugar
	 */

	public String toString()
	{
		StringBuilder buffer = new StringBuilder();
		buffer.append("[DeZipcodeBean:");
		buffer.append(" iso3166A2name: ");
		buffer.append(iso3166A2name);
		buffer.append(" zipcode: ");
		buffer.append(zipcode);
		buffer.append(" city: ");
		buffer.append(city);
		buffer.append(" latitude: ");
		buffer.append(latitude);
		buffer.append(" longitude: ");
		buffer.append(longitude);
		buffer.append("]");
		return buffer.toString();
	}

}
