package de.alpharogroup.address.book.init;

public class DeZipcodeBean {
	/** The iso3166 name with two characters. */
	private String iso3166A2name;
	
	private String zipcode;

	private String city;

	private String latitude;
	
	private String longitude;
	
	public String getIso3166A2name() {
		return iso3166A2name;
	}

	public void setIso3166A2name(String iso3166a2name) {
		iso3166A2name = iso3166a2name;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	/**
	 * @generated by CodeSugar http://sourceforge.net/projects/codesugar */
	
	public String toString() {
		StringBuilder buffer = new StringBuilder();
		buffer.append("[DeZipcodeBean:");
		buffer.append(" iso3166A2name: ");
		buffer.append(iso3166A2name);
		buffer.append(" zipcode: ");
		buffer.append(zipcode);
		buffer.append(" city: ");
		buffer.append(city);
		buffer.append(" latitude: ");
		buffer.append(latitude);
		buffer.append(" longitude: ");
		buffer.append(longitude);
		buffer.append("]");
		return buffer.toString();
	}
	
	
	
}
